import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Formula Insight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <nav className="flex w-full p-6 px-52 bg-bg text-black justify-between">
          <h1 className="text-2xl font-medium">Formula Insight</h1>
          <div className="flex items-center">
            <a href="/about-us" className="mx-4 hover:text-accent duration-150">About Us</a>
            <a href="/projects" className="mx-4 hover:text-accent duration-150">Projects</a>
            <a href="/events" className="mx-4 hover:text-accent duration-150">Events</a>
            <a href="/contact" className="ml-4 hover:text-accent duration-150">Contact</a>
          </div>
        </nav>
        <div className=" text-black">{children}</div>
      </body>
    </html>
  );
}
